from datetime import datetime
from typing import Optional, Dict, Any
from pydantic import BaseModel, Field

class PaymentConfigResponse(BaseModel):
    key_id: Optional[str] = None
    is_test_mode: bool = True
    is_configured: bool = False
    merchant_name: str = "RecoverAI Demo Store"

class CreateOrderRequest(BaseModel):
    product_id: str = Field(..., description="Unique product identifier")
    product_name: str = Field(..., description="Display title for product")
    amount: float = Field(..., gt=0, description="Amount in INR (Rupees)")
    currency: str = Field(default="INR", description="Currency code (e.g. INR)")
    customer_name: str = Field(..., description="Full customer name")
    customer_email: str = Field(..., description="Customer email address")
    customer_phone: Optional[str] = Field(default="+91 99999 99999", description="Customer mobile number")

class CreateOrderResponse(BaseModel):
    order_id: str = Field(..., description="Razorpay Order ID (order_...)")
    transaction_id: str = Field(..., description="RecoverAI Transaction ID")
    amount: int = Field(..., description="Amount in minor units (paise)")
    amount_in_rupees: float = Field(..., description="Amount in major units (INR)")
    currency: str = "INR"
    key_id: str = Field(..., description="Razorpay Test Key ID (for frontend checkout initialization)")
    product_name: str
    customer: Dict[str, Any]

class VerifyPaymentRequest(BaseModel):
    razorpay_order_id: str = Field(..., description="Razorpay Order ID returned by checkout")
    razorpay_payment_id: str = Field(..., description="Razorpay Payment ID returned by checkout")
    razorpay_signature: str = Field(..., description="HMAC-SHA256 signature generated by Razorpay")
    transaction_id: str = Field(..., description="RecoverAI Transaction ID to update")

class VerifyPaymentResponse(BaseModel):
    success: bool
    signature_valid: bool
    transaction_id: str
    razorpay_order_id: str
    razorpay_payment_id: str
    amount: float
    method: str
    status: str
    verified_at: datetime
    message: str

class PaymentFailureRequest(BaseModel):
    transaction_id: str = Field(..., description="RecoverAI Transaction ID to mark failed")
    order_id: str = Field(..., description="Razorpay Order ID")
    payment_id: Optional[str] = Field(default=None, description="Razorpay Payment ID if attempt occurred")
    error_code: Optional[str] = Field(default="PAYMENT_FAILED", description="Gateway or bank error code")
    error_description: Optional[str] = Field(default="Customer aborted or test payment declined", description="User facing description")
    error_category: Optional[str] = Field(default="GATEWAY_ERROR", description="Failure category for RecoverAI categorization")
